services:
  - type: web
    name: videograb
    env: python
    buildCommand: |
      # Install dependencies with specific versions
      pip install -r requirements.txt
      # Create necessary directories
      mkdir -p tmp
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
